---
- name: Ensure group "admin" exists
  ansible.builtin.group:
    name: admin
    state: present

- name: Add the user 'johndoe' with a specific uid and a primary group of 'admin'
  user:
    name: johndoe
    comment: John Doe
    uid: 1040
    group: admin


- name: Create a 2048-bit SSH key for user johndoe in ~johndoe/.ssh/id_rsa
  user:
    name: johndoe
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
