---
# tasks file for ansible-role-percona-server-setup
- name: Installing pip
  yum:
    name: python3-pip
    state: present

- name: Install Percona MySQL repository
  yum:
    name: "https://repo.percona.com/yum/percona-release-latest.noarch.rpm"
    state: present


- name: Install Percona MySQL Server
  yum:
    name: Percona-Server-server-57
    state: present

- name: Installing python-mysql for dependency
  yum:
    name: MySQL-python
    state: present

# setup account
- name: 'setup group'
  group: name={{GROUP}} state=present
- name: 'setup user'
  user: name={{USER}} group={{GROUP}} shell=/bin/nologin state=present


- name: 'setup service'
  service: name=mysqld state=started

- name: Find temporary password
  shell: "echo `grep 'temporary.*root@localhost' /var/log/mysqld.log | sed 's/.*root@localhost: //'`"
  register: mysql_root_password_temp
  tags: register


- name: Set new password from temporary password
  shell: 'mysql -e "SET PASSWORD = PASSWORD(''{{ mysql_root_password }}'');" --connect-expired-password -u root -p"{{ mysql_root_password_temp.stdout }}"'

- name: Create .my.cnf
  template: src=my.cnf dest=/root/.my.cnf
